config/routes.rb
Rails.application.routes.draw do



  get '/' => "sessions#welcome", as:"root"

#users route


 get '/signup' => 'users#new'
 post '/signup' => 'users#create'

 #login route
 get '/login' => 'sessions#new'
 post '/login' => 'sessions#create'

 #logout route
 delete '/logout' => 'sessions#destroy'

#callback route
get '/auth/google_oauth2/callback', to: 'sessions#google'

  resources :reviews
  resources :users
  resources :plants do 
    resources :reviews, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  
  validates :name, uniqueness: true, presence: true

  

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :plant

    scope :last_3, -> { order(created_at: :desc).limit(3)}

end

app/models/user.rb
class User < ApplicationRecord
    has_many :plants
    has_many :reviews
    has_many :reviewed_plants, -> { distinct }, through: :reviews, source: :plant
    has_secure_password

    validates :name, :email, presence: true

    def self.find_or_create_with_oauth(auth)
        user = User.find_or_create_by_email(auth)
        user.email = auth["info"]["email"]
        # user.uid = auth["uid"]
        #  binding.pry
        user.save
        user
      end

    def self.find_or_create_by_email(auth)
        User.find_or_create_by(email: auth["info"]["email"]) do |user|
        #   user.uid = auth["uid"]
        user.password = SecureRandom.hex(20)
        user.name = auth["info"]["name"]
        user.save
        user
        end
      end
    
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  #gives access to methods in the views
  helper_method :current_user, :logged_in?


  private
   def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
   end

   def logged_in?
     !!session[:user_id]
   end

   def redirect_if_not_logged_in
      redirect_to '/' if !logged_in?
   end



end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_plant, only: [:show, :edit, :update, :destroy]

    def new
     @plant = Plant.new

      end

    def create
     @plant = current_user.plants.build(plant_params)
     if @plant.save
        redirect_to plant_path(@plant)
     else
        render :new
     end
    end

    def show
        # @plant = Plant.find_by_id(params[:id])
        # redirect_to plants_path if !@plant
    end

    def index 
        # binding.pry
         
          @plants = Plant.all
    end

    def edit 

    end

    def update
        if @plant.update(plant_params)
            redirect_to plants_path(@plant)
        else
            render :edit
        end

    end

    def destroy
        @plant.destroy
        redirect_to plants_path
    end
    
   private

   def set_plant
    @plant = Plant.find_by_id(params[:id])

   end

   def plant_params
    params.require(:plant).permit(:name, :description, :location, :light_requirement, :watering, )
   end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index

       if params[:plant_id] && @plant = Plant.find_by_id(params[:plant_id])
        # @plant = Plant.find(params[:plant_id])
        @reviews = @plant.reviews
       else
        @reviews = Review.all
      end
    end
      def show
        @review = Review.find(params[:id])
      end
      def new
        @plant = Plant.find_by_id(params[:plant_id])
        @review = Review.new
      end

      def edit
        @review = Review.find(params[:id])
      end
      def update
        @review = Review.find(params[:id])
        if @review.update(review_params)
          redirect_to plant_reviews_path(@review.plant)
        else
          render :edit
        end
      end
      def create
        @review = current_user.reviews.build(review_params)
        if @review.save
          redirect_to reviews_path
        else
          render :new
        end
      end
      
      private
      def review_params
        params.require(:review).permit(:rating, :plant_id, plant_attributes:[:name])
    
      end

      def set_review
        @review = review.find_by(id: params[:id])
        if !@review
          redirect_to reviews_path
        end
      end


    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome

    end


    def destroy
        session.clear
        redirect_to root_path
      end

    def new
        
    end
    
    def create
        user = User.find_by(name: params[:user][:name])
        if user && user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
          flash[:message] = "Incorrect login info, please try again"
          redirect_to "/login"
        end
      end

      def google 
        @user = User.find_or_create_with_oauth(auth)
        session[:user_id] = @user.id
        #binding.pry
        redirect_to user_path(@user)
      end 
      
      private 

      def auth
        request.env['omniauth.auth']
      end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
      end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          #redirect to the show page
          redirect_to @user
        else
          render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
      end

      
    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
    
    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper


    def display_plants
        if @user.plants.empty?
          tag.h2(link_to('No Plants yet - create a plant here', new_plant_path))
        else
          user = @user == current_user ? 'Your' : "#{@user.name}'s"
          review_tag(:h2, "#{user} #{pluralize(@user.plants.count, 'Plant')}:")
    
        end
      end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantCabinetRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <center>
  <% if logged_in? %>
<%= link_to "home", user_path(current_user.id), method:'get' %>
  <%= link_to "add a plant", new_plant_path %>
  <%= link_to "add a review", new_review_path %> 
  <%= link_to "all plants", plants_path %> 
  <%= link_to "all reviews", reviews_path %> 
  <%= link_to "log out", logout_path, method: :delete %>
</center>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_for(@plant, local: true) do |form| %>
<%= render partial: "layouts/errors", locals: {object: @plant} %>
<br>
<div class="form group">
  <%= form.label :name %>
  <%= form.text_field :name, class:"form-control" %>
</div><br>
<div class="form group">
  <%= form.label :description %>
  <%= form.text_field :description, class:"form-control"  %>
</div><br>
<div class="form group">
  <%= form.label :location %>
  <%= form.text_field :location, class:"form-control" %>
</div><br>
<div class="form group">
  <%= form.label :light_requirement %>
  <%= form.text_field :light_requirement, class:"form-control" %>
</div><br>
<div class="form group">
  <%= form.label :watering %>
  <%= form.text_field :watering, class:"form-control" %>
</div><br>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/plants/edit.html.erb
<%= render 'form', plant: @plant %>

app/views/plants/index.html.erb
  <h2> All Plants </h2>
   <ol type = 1 ><br>
  <% @plants.each do |plant| %><br>
  <br>  <li><%= link_to plant.name, plant_path(plant.id)%></li>
    <%= plant.user.name %> 
      <% end %><br>
     </ol>

app/views/plants/new.html.erb
<%= render 'form', plant: @plant %>

app/views/plants/show.html.erb
<h2>Plants Show Page</h2>
  <p>
    <p><strong>Name:</strong>
    <%= @plant.name %></p>
    <p><strong>Description:</strong>
    <%= @plant.description %></p>
    <p><strong>Location:</strong>
    <%= @plant.location %></p>
    <p><strong>Watering:</strong>
        <%= @plant.watering %></p>
    <h4>By: <%=link_to @plant.user.name, user_path(@plant.user)%> </h4>
  </p>

  <p><%= link_to 'Add a new review', new_plant_review_path(@plant)%></p>
<% if !@plant.reviews.empty? %>
  <p><%= link_to 'See all reviews', plant_reviews_path(@plant)%></p>
  <h4>Most Recent reviews:</h4>
  <% @plant.reviews.order(updated_at: :desc).limit(3).each do |r|%>
    <li>
      <strong><%= r.user.name%></strong> says "<%= link_to r.rating, plant_reviews_path(@plant,r) %>"
    </li>
  <% end %>
  <% end %>

  <br>
  <% if @plant.user == current_user %>
    <%= link_to 'Edit', edit_plant_path(@plant) %> |
    <%= link_to 'Delete', plant_path(@plant),method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
 <br>
 <% end %> 
 <br>
   <%= link_to 'Back', plants_path %>
 

app/views/reviews/_form.html.erb
 <%= form_for([@plant, @review]) do |f| %>
 <%= render partial: "layouts/errors", locals: {object: @review} %>

 <% if !@review.plant %>
  <%= f.label :plant %>
  <%= f.collection_select :plant_id, plant.all, :id, :title %>
<% else %>
    <%= f.hidden_field :plant_id %>
<% end %>

    <div class="range-field col s12">
      <%= f.label :rating %>
      <%=f.range_field :rating, in: 1..10, :step => 0.1%><br>
    </div>

    <% end %>

app/views/reviews/edit.html.erb
<%= render 'form', review: @review %>

app/views/reviews/index.html.erb
<% if @plant %>
  <h1>Reviews for <%= @plant.name%></h1>
<% else %>
  <h1>All Reviews</h1>
<% end %>
<ul>
<% @reviews.each do |r|%>
  <li><%= r.user.name%> rates this plant <%= r.rating%> out of 5: <strong><%= link_to r.plant.name, plant_path(r.plant_id) %></strong></li>
<% end %>
</ul>

app/views/reviews/new.html.erb
<% if @review.plant %>
<h1>New review for <%= @review.plant.name%>!</h1>
<% else %>
<h1>New review!</h1>
<% end %>

<%= form_for([@review.plant,@review]) do |f|%>
 <% if !@review.plant %>
  <%= f.label :plant %>
  <%= f.collection_select :plant_id, Plant.all, :id, :name %>
<% else %>
    <%= f.hidden_field :plant_id %>
<% end %>
 <%= f.label :rating %>  
 <%= f.select(:rating, [1,2,3,4,5], :prompt => 'Rating (1-5)') %>
 <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h2><%= @review.content%> - <%= @review.user.name%></h2>
<% if @review.user == current_user %>
  <%= link_to "Edit review", edit_review_path(@review)%>
<% end %>
<h4>Read the plant here: <%= link_to @review.plant.name, plant_path(@review.plant_id) %></h4>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render partial: "layouts/errors", locals: {object: @user} %>
<%= form_for(@user, url:'/signup') do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
   <br>
  <%= f.label :email %>
  <%= f.email_field :email, required:true%>
  <br>
   <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
   <br>
    <br>

  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1> Welcome <%= "#{@user.name}" %></h1> 
</div>
<p><u> Plants and Reviews by <%=@user.name%> </u></p>
</div>
<p><u>Reviewed plants:</u></p>
 <ol type =1 >
  <% @user.reviewed_plants.each do |plant|%>
  <li> <%= link_to plant.name, plant_path(plant)%></li>
  <% end %>
  </ol>
</div>
<div>
<p><u>My Plants</u></p>
<ol type =1 >
  <% @user.plants.each do |plant|%>
  <li> <%= link_to plant.name, plant_path(plant) %></p></li>
  <% end %>
</ol>
</div>